version: '3.1'

services:

  db:
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password
    ports:
        - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example