name: CI
on: [push, pull_request]
env:
  CI: true
  SCALA_VERSION: 2.13.2

jobs:
  validate:    
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v2        
      - uses: olafurpg/setup-scala@v7
      - name: Cache Coursier
        uses: actions/cache@v2
        with:
          path: ~/.cache/coursier
          key: sbt-coursier-cache
      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: ~/.sbt
          key: sbt-${{ hashFiles('**/build.sbt') }}      
      - name: Check lint
        run: sbt ++$SCALA_VERSION "scalafixAll --check"
      - name: Check formatting
        run: sbt ++$SCALA_VERSION scalafmtCheckAll        
      - name: Test
        run: sbt ++$SCALA_VERSION clean coverage test coverageReport
      - name: Scaladoc
        run: sbt ++$SCALA_VERSION doc 
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
          verbose: true