name: CI
on: [push, pull_request]

env:
  CI: true
  SCALA_VERSION: 2.13.2

jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v2        
      - uses: olafurpg/setup-scala@v7
      - name: Cache Coursier
        uses: actions/cache@v2
        with:
          path: ~/.cache/coursier
          key: sbt-coursier-cache
      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: ~/.sbt
          key: sbt-${{ hashFiles('**/build.sbt') }}      
      - name: Check formatting
        run: sbt ++$SCALA_VERSION scalafmtCheckAll          
      - name: Check headers
        run: sbt ++$SCALA_VERSION headerCheck test:headerCheck
      - name: Compile
        run: sbt ++$SCALA_VERSION test:compile
      - name: Check compatibility
        run: sbt ++$SCALA_VERSION mimaReportBinaryIssues
      - name: Check unused dependencies
        run: sbt ++$SCALA_VERSION unusedCompileDependenciesTest
      - name: Test
        run: sbt ++$SCALA_VERSION test
      - name: Scaladoc
        run: sbt ++$SCALA_VERSION doc 
